# Don't use container-based infrastructure, sudo enabled has 18G disk
# whereas sudo disabled has only 9G
sudo: true
language: python
python:
  - "2.7"
  - "3.5"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
  # cache pip files; directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries; vaxrank directory containing FM index of reference kmers
  directories:
    - $HOME/.cache/pyensembl/GRCh37/ensembl75/
    - $HOME/.cache/pyensembl/GRCh38/ensembl93/
    - $HOME/.cache/pyensembl/GRCm38/ensembl93/
  timeout: 300
before_install:
  - |
    # possibly required to fix Travis for py3.5 but we should get rid
    # of this when using py3.6+
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      pip install setuptools --upgrade
    fi
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # install netmhcbundle
  - git clone https://mhcbundle:$MHC_BUNDLE_PASS@github.com/openvax/netmhc-bundle.git
  - export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
  - mkdir tmp
  - export NETMHC_BUNDLE_TMPDIR=$PWD/tmp
  - export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
  # tells vaxrank where to install the reference peptide cache
  - export VAXRANK_REF_PEPTIDES_DIR=$HOME/.cache/vaxrank
env:
  global:
    # MHC_BUNDLE_PASS
    - secure: "X3FwUdvnhxDbHOfxSjMgJg8N4WSGcmQL7Nl7B/oWQUBico1n6H8JlOtrN9mLU+AfB+bAuZjonPaGakB5j9imZfHwyKbOtIbbXzvPMJBNpdlq6ongaAIMFVMr4963hOn+KEJqNmmeCF/AEPqQxFXQRYJKPNoxP8kp/lX391CQrxeH0NPSUZUFR5huQzElYSRNFug805u/0hdAQTyFRl9cIFxb+4zHxzd+roCrY6DNb24igBGz2/ArQRBJf/iPVRZEE3nKPYGRDXepnIyRaGVetaEM/k8FYR87oBkyyIXCTWLDIP1KwvoN8Uo94ODUyL/Hv2LjE7oF3fV1lwX6u6U5yN+girjlrfdgBiCkLPlxcBsZ7uGAepz+aD76Omhz2r3dyAjJMTBwoufRLPFNUumY7YK8TqB6DZFU9mu8DVTpzjMjrsMicV5NaSzSA/CKswwyCqu3U3OaHTEpwExuFKyAFMolQKTct2HpAqkQoLxHq8Jp0bfxz+xFsUC4akx5UXUsPBjgQEB27QaC0plJoHLj9gm/2bJWYUEmoOmpcu/dyZLaGBoPUH25MqYc8IJ+jdLnoOaEZDU5O8F32Ky9W4C8OFakz6ABhCsmD1JblnEJMJuNBiCA56QjYeuMIO3ilPwXXz/N/kyxCPVgwKRouqNZ9PlapB3agdy1m5Bn+wOvuaM="
    - KERAS_BACKEND=tensorflow
addons:
  apt:
    packages:
    # Needed for NetMHC
    - tcsh
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy nose pylint cython
  - source activate test-environment
  # install pysam from conda because I'm having trouble installing Cython
  # for Python 3 on Travis
  - conda install -c bioconda pysam=0.9.0
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
before_script:
  - ./lint.sh
  - >
      pyensembl install
      --release 75
      --species human
      --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh37.75/
  - >
      pyensembl install
      --release 93
      --species human
      --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCh38.93/
  - >
      pyensembl install
      --release 93
      --species mouse
      --custom-mirror https://github.com/openvax/ensembl-data/releases/download/GRCm38.93/
script:
  - travis_wait nosetests -sv test -a '!skip' --with-coverage --cover-package=vaxrank
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: openvax
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "kt07TyCxiumbu2SGZvl7J5LLzsLq0zxcCceOSGb4RE0tFOmiUmDv5LfGKME5lEFhPxleChaq/AILDOudEZO3H9xJY90/dXPgyXJOd6pCOzKq3zIKEjz3MEx3wBizcjR7ucHxYxDQzIBEBeoC4wTIc53mBR5gMgqyG8Dbciueg9Yo5qZED9rq/uY1ELxW2iQsS9LBK7n/blTPTisdmdG3g64eVEDsZD/0egPdupWhlkNuUQlA4LVr2KUifGrtXPL0A/m3CUEABJWre7PJ6motFS1KramP7/PQJwpXmZEHI1ayknNeN2ndMp4Ni64cEhtF/JIRYWBuGxzZXSuIv1g8XxKijm/qxSc4Gv0yIiP/Q3pZ5hfSC1RZhcpkc3ugCSOy5VwlF5O0P/EflMnsUE9ZRFON3s5+yjsJtNldsCRpdEsquFPn0BJC4kOdWKfIkYuhln6xcJawl+8uKlCJuOa1vZcsJ16E6RPN3TpkfChaMVBrD6zEbYZfrI5QCMV/uwkwutgV4H95FR0TlnDrOTwAMamxFBN7R8+YEHff9n21c4i7vzjBVlI16W/t2qqmaG/0w1hBhAiYvvV5BLh84km5gSewcjcKjBHVhYscF1Xxyq0CPmKdcOB6ePFbIWh/+NHQzDpzY8yKp9kzkZizZJGUAxsI2ZH3++BzQwcSUn664VY="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
